"""empty message

Revision ID: a998e91d35e9
Revises: 7cfd5d41f602
Create Date: 2024-03-21 22:00:33.672905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a998e91d35e9'
down_revision = '7cfd5d41f602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.Integer(), nullable=True))
    op.execute('UPDATE shows SET id = 1 WHERE id IS NULL;')
    op.alter_column('shows', 'id', existing_type=sa.Integer(), nullable=False, primary_key=True)
    op.alter_column('shows', 'venue_id', existing_type=sa.Integer(), nullable=False, primary_key=False)
    op.alter_column('shows', 'artist_id', existing_type=sa.Integer(), nullable=False, primary_key=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'id')
    op.alter_column('shows', 'venue_id', existing_type=sa.Integer(), nullable=False, primary_key=True)
    op.alter_column('shows', 'artist_id', existing_type=sa.Integer(), nullable=False, primary_key=True)

    # ### end Alembic commands ###
