"""increase_url_lengths

Revision ID: aaa658c6071f
Revises: ef50e2bee082
Create Date: 2024-03-27 23:34:49.449958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa658c6071f'
down_revision = 'ef50e2bee082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('facebook_link',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=2083),
               existing_nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=2083),
               existing_nullable=True)

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.alter_column('facebook_link',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=2083),
               existing_nullable=True)
        batch_op.alter_column('website',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=2083),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.alter_column('website',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('facebook_link',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.alter_column('website',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('facebook_link',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
