"""empty message

Revision ID: ba1557553bb0
Revises: 477e3f4dcedc
Create Date: 2024-03-22 18:38:59.125839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1557553bb0'
down_revision = '477e3f4dcedc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shows", sa.Column("id", sa.Integer, nullable=True))
    op.execute("UPDATE shows SET id = 1 WHERE id IS NULL;")
    op.create_primary_key("shows_pkey", "shows", ["id"])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint('shows_pkey', 'primary')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
